[tool.pyright]
include = ["utils/",
        "models/"]

reportMissingImports = false
reportMissingTypeStubs = false

# pythonVersion = "3.10"
# pythonPlatform = "Linux"

# venvPath = "/home/cheurte/miniconda3/envs/"
# venv = "process"

executionEnvironments = [
]
